import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Card from '@/components/Card';
import IHome from '@/Types/IHome';

const inter = Inter({ subsets: ['latin'] })

export default function Home(props:IHome) {
  const {currancyList} = props;
  return (
    <>
      <Head>
        <title>Money Exchange App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <h1 className={styles.title}>Money Exchange</h1>
          <Card currancyList={currancyList}/>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const url = 'https://currency-exchange.p.rapidapi.com/listquotes';
  const options = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': 'b53f13bb43msh451041ebc7baab2p1cfb3ejsn338903d0faf6',
      'X-RapidAPI-Host': 'currency-exchange.p.rapidapi.com'
    }
  };
  try {
    const response = await fetch(url, options);
    const result = await response.json();
    return { props: { currancyList:result } }
  } catch (error) {
    console.error(error);
  }
}