import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Card from '@/components/Card';
import IHome from '@/Types/IHome';
import { getAvailableCurrancy } from './api/currency';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ currancyList }:IHome) {
  return (
    <>
      <Head>
        <title>Money Exchange App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.container}>
          <h1 className={styles.title}>Money Exchange</h1>
          <Card currancyList={currancyList}/>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const currancyList = await getAvailableCurrancy();
    return { props: { currancyList } }
  } catch (error) {
    return { props: { currancyList: [] } };
  }
}